### ISSUE TITLE
Not offering event due to pending event

### ISSUE THREAD

**Issue by colinbes** [swoval/swoval#134]
I have installed set-close-watch (versions 2.1.2 and 2.1.3) plugin ( and on running sbt ~run (via terminal on macOS Mojave) when I save first .scala file I see no attempt to relaunch scala app. If I save another file (or same as last one) I get error message 

```
[info] Not offering event Triggered(/Users/colinbes/CloudStation/coding/akka-actor/src/main/scala/com/besterdesigns/rest/services/BasicService.scala,1564666847621) due to pending event Triggered(/Users/colinbes/CloudStation/coding/akka-actor/src/main/scala/com/besterdesigns/rest/services/SiteService.scala,1564666843467)
```

If I run ~compile then all works as expected.
I have tried editing file via IntelliJ, VS Code, and Nano editor via terminal - all with same behavior.

**Comment by eatkins** [comment]
Thanks for the report! What version of sbt are you using?

**Comment by colinbes** [comment]
Apologies I should have included that, it’s version 1.2.8 with Java jvm 1.8x

Also without the plugin installed ~run doesn’t seem to work at all while ~compile does.

**Comment by eatkins** [comment]
Are you using the play framework by any chance? They do some weird stuff with overriding the `run` command when invoked as `~run`.

**Comment by colinbes** [comment]
Nope, it's a plain old akka based scala project.

I am in process of stripping down project to see if anything is intefereing.

**Comment by eatkins** [comment]
It's weird to me that you're having issues with 1.2.8 without CloseWatch. Could you give sbt 1.3.0-RC3 a shot? We've completely overhauled the internal watch mechanism for 1.3.0.

**Comment by colinbes** [comment]
So, I've spent the better part of the day digging into this and think I have boiled it down to fact that my app runs continuously due to having akka actors and it seems sbt 1.2.8 doesn't know how to shutdown and restart application. If I comment out actor code then ~run works. 

This is not a plugin issue so am going to close this thread but would be interested in any ideas/comments to whether there is a way to do this or not - I seem to recall somewhere using ~restart .....

**Comment by eatkins** [comment]
You can shutdown the application with `ActorSystem.terminate`. We actually have an automated test for `run` using Akka in sbt: https://github.com/sbt/sbt/blob/develop/sbt/src/sbt-test/classloader-cache/akka-actor-system/src/main/scala/AkkaTest.scala.

**Comment by eatkins** [comment]
Also, I think you may be thinking of https://github.com/spray/sbt-revolver which adds the reStart command.

**Comment by colinbes** [comment]
Yup, that's it - was just about to post about sat-resolver in case it helped anyone else - sad when one can't recall at drop of hat anymore :-)
