### ISSUE TITLE
Registering paths with shared prefixes

### ISSUE THREAD

**Issue by uncle-betty** [swoval/swoval#152]
Hello there.

I would like to run something by you that I encountered in the context of https://github.com/scalameta/metals/issues/3379, which I think might be a bug. Suppose that I do the following:

  * I have the following existing directory: `A/B2`. (`A` is empty other than containing `B2`.)
  * First, I register `A/B1`. (Note that `B1` doesn't exist in `A`.)
  * Then, I register `A/B2/C`. (Note that `C` doesn't exist in `B2`.)

Here's what happens in `NioPathWatcher.findOrAdd()`:

  * As `A/B1` does not exist, the watch's path is truncated to the longest prefix of `A/B1` that exists. `A` exists, so the longest existing prefix is `A`. So a watch is created for `A` instead of `A/B1`. (And `A` is added to `rootDirectories`.)

  * When the second watch is registered, the code searches `rootDirectories` for prefixes of `A/B2/C` - and it finds `A`. So, no new watch gets registered.

  * When I now create `A/B2/C`, the code does not notice it, because it did not set up a watch for `A/B2`.

I confirmed the registration of `inotify` watches by monitoring `file-tree-views`'s calls to the `inotify` API of glibc. While I'm not sure that my analysis of what's going on in `findOrAdd()` is 100% accurate, I am pretty certain that the only `inotify` watch that gets created is the one for `A`.

**Comment by eatkins** [comment]
Thank you for the detailed repro! This was indeed a longstanding bug that the test cases did not cover but I was able to make a new test case following your template. It should be fixed by #153 and I released a new version of the library (2.1.8) containing the fix to maven central.

**Comment by eatkins** [comment]
Closing because I'm pretty sure 2.1.8 fixes the issue but feel free to reopen if I'm wrong.

**Comment by uncle-betty** [comment]
Oh, wow! Thank you for the quick turn-around. I just verified that 2.1.8 fixes my test case, my MWE for the Metals issue, as well as my original Metals issue. Problem solved! I'm very excited. Thanks again.
