### ISSUE TITLE
NioPathWatcher registration of paths with shared prefixes produces spurious create events

### ISSUE THREAD

**Issue by pvid** [swoval/swoval#155]
Reproduction

```scala
//> using scala "2.12"
//> using lib "com.swoval:file-tree-views:2.1.8"

package com.swoval.files

import com.swoval.files.FileTreeViews.Observer
import com.swoval.logging.Loggers

import java.io.IOException
import java.nio.file.Paths
import java.nio.file._
import java.nio.file.attribute.BasicFileAttributes

object Main {
  def main(args: Array[String]): Unit = {
    Files.createDirectories(Paths.get("A/C"))
    Files.createDirectories(Paths.get("A/B"))

    val watcher = PathWatchers.get(true)
    watcher.addObserver(new Observer[PathWatchers.Event] {

      override def onError(error: Throwable): Unit = {
        println(s"Observed error $error")
      }

      override def onNext(event: PathWatchers.Event): Unit = {
        println(s"Observed event $event")
      }
    })
    watcher.register(Paths.get("A/C"), Int.MaxValue)
    watcher.register(Paths.get("A/B"), Int.MaxValue)
  }
}
```

produces output

```
Observed event Event(/home/pavol/git/file-watcher-test/A/C, Create)
```

Similar problem arises when registering `A/C` and then `A` (in that case `Create` for `A/C` is reported).  Registering `A` and then `A/C` works as expected - no events produced.

I originally encountered the problem while registering non-existent directories, but this reproduction does suggest that it does not depend on the directories existing.

Please do let me know if I can help in any way. I might try to dive in and submit a PR, but no promises since I am not familiar with the implementation

**Comment by eatkins** [comment]
Thank you for the report and the good repro! This should be fixed by #156. I pushed a new version, 2.1.9 to maven central.

**Comment by pvid** [comment]
Blazing response time, wow! Thank you :+1:

**Comment by eatkins** [comment]
I like to keep the issue count at zero :)
