### ISSUE TITLE
Option to not follow symlinks

### ISSUE THREAD

**Issue by eed3si9n** [swoval/swoval#166]
## Problem

Ref https://github.com/sbt/sbt/issues/7331

scripted test in sbt uses

```scala
val toDelete = view.list(base / **, !keep).map(_._1).sorted.reverse
```

to delete files, which automatically follows symlink, and deletes the content of the symlinked directories.

## feature request

If there's a way to tell not to follow symlinks that'd be good.
Alternatively I guess we can list all the symlinked directories, and then to `keep` to keep the items under the symlinks.

**Comment by eatkins** [comment]
This option already exists:
https://github.com/swoval/swoval/blob/b1ea3dee1495928d025b5ea95148ba3f58b7314f/files/jvm/src/main/java/com/swoval/files/FileTreeViews.java#L92-L103

I'm going to close the issue for now. If the toggle doesn't work or there is something I'm missing, feel free to reopen.
