### ISSUE TITLE
Typo in executor name of SymlinkWatcher

### ISSUE THREAD

**Issue by rmgk** [swoval/swoval#167]
Missing `c` in `SymlinkWather`, should be `SymlinkWatcher`

https://github.com/swoval/swoval/blob/b1ea3dee1495928d025b5ea95148ba3f58b7314f/files/js/src/main/scala/com/swoval/files/SymlinkWatcher.scala#L66

**Comment by eatkins** [comment]
Thank you for the report. Fixed in #168.
