### ISSUE TITLE
Add freebsd support

### ISSUE THREAD

**Issue by eatkins** [swoval/swoval#97]
Preliminary support for freebsd was added in #96. In order to ship, we need to validate the library on a vm and provide installation instructions for freebsd users as well as instructions for how to rebuild the native binaries.

Non goals: scala.js support for freebsd. It'd be nice if it worked, but not worth spending time on it.

**Comment by alexdupre** [comment]
The current openjdk8 port uses the PollingWatchService on FreeBSD. With it, many tests fail because the timeouts are too low for such backend. I've added support for a native WatchService that uses the kqueue kernel facility for real-time monitoring that allows the tests to pass without increasing the timeouts.

**Comment by eatkins** [comment]
Very nice. That sounds like a nice improvement over what sbt is probably doing today (assuming that sbt is your use case).

**Comment by alexdupre** [comment]
Yes, in fact currently we run sbt with -Dsbt.watch.mode=polling, because sbt polling is better than the java.nio polling (0.5s vs ~10s notification time). With a native watch service this is not necessary anymore.

**Comment by alexdupre** [comment]
To just build the shared libraries it's not necessary to have a patched openjdk8. That is needed to pass tests, though.

**Comment by eatkins** [comment]
Ok, that seems fine. I'll build the libraries myself and publish a new version. We are planning to release sbt 1.3.0 in January which would definitely include these changes.

**Comment by eatkins** [comment]
Added in v2.0.5. Once your watch service patch makes it into the freebsd openjdk8 port, we should add documentation suggesting that people upgrade their jdk for sbt on freebsd.

**Comment by alexdupre** [comment]
I've investigated the Javascript issue and I've found that there are two problems:

1. if a fs action is performed immediately after returning from the `PathWatcher.register` call, the javascript callback function is not called and so no event is generated; waiting 1 ms after the `register` call before modifying the fs is enough to trigger the event

2. the callback of the `fs.watch` function is called with a `null` filename (that is later stringified), so the events are ignored. This is expected by the nodejs fs api:

```Providing filename argument in the callback is only supported on Linux, macOS, Windows, and AIX. Even on supported platforms, filename is not always guaranteed to be provided. Therefore, don't assume that filename argument is always provided in the callback, and have some fallback logic if it is null.```

**Comment by eatkins** [comment]
Cool. Thanks for the update. The scala.js portion of file-tree-views is really more of a hobby project for me and I don't think anyone is using it. It also has helped me feel confident about the correctness of file-tree-views since the concurrency model is completely different in scala.js and scala.jvm but they're able to mostly share the same test suite.

**Comment by eatkins** [comment]
Actually I had to fix a different bug so I went ahead and added some simple fixes:
https://github.com/swoval/swoval/pull/101/commits/9ed221dc059c8de8c5eb075829f89359f4a1d06c
Not sure if this actually fixes anything, but it didn't break anything on linux or windows.

**Comment by alexdupre** [comment]
Hmmm, I'm not sure if the new `setTimeout` call I see is related to my comment above, but it doesn't seem so. The changes have no effects on FreeBSD. The fix for point 1) is to add the following function:

```
  def newDelayedFuture[T](timeout: FiniteDuration)(f: => Future[T]): Future[T] = {
    val p = Promise.apply[T]
    setTimeout(timeout) {
        p.completeWith(f)
    }
    p.future
  }
```

and call it in tests, eg replacing:

```
    val file = dir.resolve(Paths.get("foo")).createFile()
    events.poll(DEFAULT_TIMEOUT)(_.getTypedPath.getPath ==> file)
```
with
```
  newDelayedFuture(5.millis) {
    val file = dir.resolve(Paths.get("foo")).createFile()
    events.poll(DEFAULT_TIMEOUT)(_.getTypedPath.getPath ==> file)
  }
```

Regarding point 2), your change has the effect that when a file is added/modified/deleted inside a watched directory, the `Modify` event is emitted with the directory as path, so it's better than before, but still doesn't work. Ideally the definitive fix would be to diff the previous directory content with the directory content got at callback time and emit the corresponding events.

**Comment by alexdupre** [comment]
FYI, my patches have been committed and are included in the latest FreeBSD binary packages, too.

**Comment by eatkins** [comment]
That's great news! Sounds like the latest freebsd should work well with sbt 1.3.0 whenever we're able to release it.
